### ISSUE TITLE
Lambda Botocore Deprecation - requests library deprecated

### ISSUE THREAD

**Issue by tcourtnage-tbl** [binxio/cfn-tag-provider#1]
Thanks for this custom resource!

AWS is deprecating the requests library in the Lambda environment (https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/).

I believe from looking at the code bundle you provide, that the ```requests``` library is bundled with the application, and is not using the ```requests``` library from the Lambda environment, so no change is necessary to this custom resource. But, I'm not a Python dev, so would like confirmation on that everything should be A-OK come April 1, 2021.

Thanks

**Comment by mvanholsteijn** [comment]
No problems. I am packaging my own libraries -> https://github.com/binxio/cfn-tag-provider/blob/master/requirements.txt
